const questions = [
  "What’s a skill you’ve always wanted to learn but haven’t started yet?",
  "If you could travel to any place in the world right now, where would it be and why?",
  "What’s the most interesting thing you’ve read or watched recently?",
  "If you could live in any fictional world, where would it be?",
  "What’s a simple thing in life that brings you a lot of joy?",
  "If you could master any instrument instantly, which one would you choose?",
  "What’s a hobby you’ve always been curious about but never tried?",
  "What’s the best compliment you’ve ever received?",
  "If you could have any superpower for a day, what would it be?",
  "What’s your favorite way to spend a lazy day?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "What’s something new you’ve learned recently?",
  "If you could time travel to any period, where would you go?",
  "What’s your favorite childhood memory?",
  "If you had to describe yourself using only three words, what would they be?",
  "What’s a book or movie that changed your perspective on life?",
  "What’s one thing you wish more people knew about you?",
  "If you could swap lives with any celebrity for a week, who would it be?",
  "What’s the most memorable trip you’ve ever taken?",
  "If you could instantly speak any language fluently, which one would you choose?",
  "What’s your go-to comfort food?",
  "If you could have any job in the world for a week, what would it be?",
  "What’s the most spontaneous thing you’ve ever done?",
  "What’s your favorite way to unwind after a long day?",
  "If you could make one positive change in the world, what would it be?",
  "What’s a fun fact about yourself that most people don’t know?",
  "If you could bring back any fashion trend, what would it be?",
  "What’s the best piece of advice you’ve ever received?",
  "What’s your favorite type of weather?",
  "If you could relive any moment from your life, what would it be?",
  "What’s the best meal you’ve ever had?",
  "If you could only listen to one song for the rest of your life, what would it be?",
  "What’s your favorite way to stay active or exercise?",
  "If you could be a character in any movie or TV show, who would you be?",
  "What’s a place you’ve always wanted to visit but haven’t yet?",
  "If you had an extra hour in the day, how would you spend it?",
  "What’s the most interesting conversation you’ve had recently?",
  "If you could instantly solve one global issue, what would it be?",
  "What’s something that always makes you smile?",
  "If you could have any animal as a pet (real or fictional), what would you choose?",
  "What’s the last thing that made you laugh out loud?",
  "If you could switch lives with someone for a day, who would it be?",
  "What’s the most unusual food you’ve ever tried?",
  "What’s one thing you’re looking forward to right now?",
  "If you could design your perfect day, what would it look like?",
  "What’s a random skill you’re surprisingly good at?",
  "If you could spend a day in any city, where would you go?",
  "What’s your favorite holiday tradition?",
  "If you could meet any fictional character, who would it be?",
  "What’s the best gift you’ve ever received?",
  "What’s something small that you’re really proud of?",
  "If you could live in any country for a year, where would it be?",
  "What’s a movie or show that always puts you in a good mood?",
  "What’s a goal you’re currently working toward?",
  "If you could bring back any extinct animal, which one would it be?",
  "What’s your favorite way to relax on the weekend?",
  "If you could attend any event in history, what would it be?",
  "What’s your favorite thing to do when you’re bored?",
  "If you could learn the answer to any unsolved mystery, what would it be?",
  "What’s a quote or phrase you live by?",
  "If you could invent something to make life easier, what would it be?",
  "What’s the best compliment you’ve ever given someone?",
  "What’s a new experience you’d like to try?",
  "If you could own any piece of art, which one would you choose?",
  "What’s your favorite way to celebrate a special occasion?",
  "If you could be a professional athlete in any sport, which one would you choose?",
  "What’s your favorite book or movie genre?",
  "If you could instantly travel to any planet, which one would you visit?",
  "What’s a skill you admire in others?",
  "If you could live in any decade, which one would it be?",
  "What’s the most adventurous thing you’ve ever done?",
  "If you could have any animal trait (like flight or night vision), which would you choose?",
  "What’s something you’re really passionate about?",
  "If you could have dinner with three people, living or dead, who would they be?",
  "What’s your favorite way to get creative?",
  "If you could have any job for a day, what would it be?",
  "What’s the most memorable thing someone has done for you?",
  "If you could live anywhere in the world, where would it be?",
  "What’s your favorite comfort movie or TV show?",
  "If you could make one law that everyone had to follow, what would it be?",
  "What’s a hidden gem in your city or town that more people should know about?",
  "If you could have one wish granted, what would it be?",
  "What’s your favorite way to connect with others?",
  "If you could instantly become an expert in any field, what would it be?",
  "What’s a tradition from your culture or family that you love?",
  "If you could change one thing about the world, what would it be?",
  "What’s something that’s always worth splurging on?",
  "If you could witness any natural phenomenon in person, what would it be?",
  "What’s a talent you wish you had?",
  "If you could create your own holiday, what would it celebrate?",
  "What’s the best compliment you’ve ever received from a stranger?",
  "If you could magically speak to animals, which one would you want to talk to first?",
  "What’s your favorite thing to do outdoors?",
  "If you could instantly travel anywhere, where would you go?",
  "What’s the most thoughtful gift you’ve ever given?",
  "If you could only wear one color for the rest of your life, what would it be?",
  "What’s something that never fails to cheer you up?",
  "If you could learn one thing instantly, what would it be?",
  "What’s your favorite way to spend a rainy day?",
  "If you could redo one moment in your life, what would it be?",
];

module.exports = { questions };
